### ISSUE TITLE
Request for train/test dataset

### ISSUE THREAD

**Issue by ebkablan** [khtao/StainNet#1]
The original image sizes obtained with the Aperio and Hamamatsu scanners are different from each other (Aperio: 1539x1376, Hamamatsu: 1663x1485). Which method did you use to obtain 256x256 image patches from the original dataset? could you 
share your train/test dataset? Because there is no one-to-one match between the two scanner images and this affects the results negatively.

**Comment by khtao** [comment]
BaiduYun url:https://pan.baidu.com/s/1_k7l3wL0vrP26Yc6kkcWEQ Extraction code：wrfi
