### ISSUE TITLE
此代码相关的论文描述的StainNet模型，测试验证是OK的

### ISSUE THREAD

**Issue by yanqingbing888888** [khtao/StainNet#3]

**Comment by yanqingbing888888** [comment]
非常抱歉，自己弄错了

**Comment by yanqingbing888888** [comment]
非常抱歉，自己弄错了!

**Comment by yanqingbing888888** [comment]
> _No description provided._

**Comment by khtao** [comment]
多谢

**Comment by AudioWiz** [comment]
The code is not working got following error

Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

**Comment by khtao** [comment]
> The code is not working got following error
> 
> ## Setting up a new session...
> Exception in user code:
> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 95, in create_connection raise err File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection sock.connect(sa) ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:

This error is about visdom server，you can read visdom doc
